### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by amogdalov-sc** [OpusCapita/filemanager#125]
OS win. 1.0.0-beta.11.
```
2017-12-22 13:58:21:204 (DEBUG) [......node_modules.winston.winston.transports.console] { message: 'Error processing request by ::ffff:127.0.0.1: Error: Invalid
 id\nError: Invalid id,    at decode (E:\\invt_bugfix\\node_modules\\@opuscapita\\filemanager-server\\utils\\id.js:15:11),    at id2path (E:\\invt_bugfix\\node_
modules\\@opuscapita\\filemanager-server\\router\\lib.js:20:20),    at err (E:\\invt_bugfix\\node_modules\\@opuscapita\\filemanager-server\\router\\uploadOrCrea
te.js:112:23),    at Immediate.<anonymous> (E:\\invt_bugfix\\node_modules\\multer\\lib\\make-middleware.js:53:37),    at runCallback (timers.js:641:20),    at t
ryOnImmediate (timers.js:610:5),    at processImmediate [as _immediateCallback] (timers.js:582:5)',
  level: 'error',
  timestamp: '2017-12-22T10:58:21.200Z' }

POST /workarea/api/files 400 21744.944 ms - -
```

**Comment by kvolkovich-sc** [comment]
Can't reproduce.

**Comment by kvolkovich-sc** [comment]
Its an issue in your application. You use `express-fileupload` package on application-level.
