### ISSUE TITLE
Step by step guide to use

### ISSUE THREAD

**Issue by MasterCna** [OpusCapita/filemanager#248]
hello everyone,
I'm quite new to react and I wanted to use this filemanager in my simple project. I really confiused that how can I get the exact result in my project. Can anyone guide me step by step installing and running the filemanager?
Thanks in advance

**Comment by kvolkovich-sc** [comment]
Now sure about step by step guide, but you can ask more concrete questions here.

Run server:

`npm install --save @opuscapita/filemanager-server`

then see example https://github.com/OpusCapita/filemanager/blob/master/packages/demoapp/index.js

Web UI:

https://github.com/OpusCapita/filemanager#how-to-use-client-react

**Comment by MasterCna** [comment]
Thanks, when I run `npm start` this log shows:
`> @opuscapita/filemanager-server@1.1.0-beta.6 start F:\Deisgn\SEGAL_PANEL\node_modules\@opuscapita\filemanager-server
> npm run prepare-demo && cross-env NODE_ENV=development node start.js


> @opuscapita/filemanager-server@1.1.0-beta.6 prepare-demo F:\Deisgn\SEGAL_PANEL\node_modules\@opuscapita\filemanager-server
> rimraf test-files && mkdirp test-files && cross-env ../../demo-filesystem/populate-demo-fs.sh ./test-files

The system cannot find the path specified.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ../../demo-filesystem/populate-demo-fs.sh ENOENT
    at notFoundError (F:\Deisgn\SEGAL_PANEL\node_modules\@opuscapita\filemanager-server\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (F:\Deisgn\SEGAL_PANEL\node_modules\@opuscapita\filemanager-server\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (F:\Deisgn\SEGAL_PANEL\node_modules\@opuscapita\filemanager-server\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @opuscapita/filemanager-server@1.1.0-beta.6 prepare-demo: `rimraf test-files && mkdirp test-files && cross-env ../../demo-filesystem/populate-demo-fs.sh ./test-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @opuscapita/filemanager-server@1.1.0-beta.6 prepare-demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iran\AppData\Roaming\npm-cache\_logs\2019-01-12T14_15_25_578Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @opuscapita/filemanager-server@1.1.0-beta.6 start: `npm run prepare-demo && cross-env NODE_ENV=development node start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @opuscapita/filemanager-server@1.1.0-beta.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iran\AppData\Roaming\npm-cache\_logs\2019-01-12T14_15_25_608Z-debug.log`
